version: '3'

services:
  db:
    image: postgres:14.5
    container_name: book-db
    environment:
      LANG: en_US.utf8
      POSTGRES_DB: bookstore-example
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      PGPORT: 5432
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U postgres

  pgadmin:
    image: dpage/pgadmin4:snapshot
    container_name: book-pgadmin
    ports:
      - 8083:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    container_name: book-keycloak
    volumes:
      - ./scripts/keycloak:/opt/keycloak/data/import # Import realm from file
    command: [ 'start-dev --import-realm' ]
    ports:
      - 8082:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password

  kafka-ui:
    container_name: book-kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8081:8080
    depends_on:
      - zookeeper
      - broker
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_JMXPORT: 9997
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: book-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: book-broker
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1