micronaut:
  application:
    name: bookstoreServiceMicronautKotlin
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/bookstore-example
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        connection:
          db-type: postgres
          url: jdbc:postgresql://localhost:5432/bookstore-example
          username: postgres
          password: password
    reactive: true
netty:
  default:
    allocator:
      max-order: 3
