micronaut:
  application:
    name: bookstoreServiceMicronautKotlin
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/bookstore-example
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver

jackson:
  time-zone: UTC
  serialization-inclusion: ALWAYS
  serialization:
    indent-output: true
    write-dates-as-timestamps: false
    use-big-decimal-for-floats: true
  deserialization:
    useBigDecimalForFloats: true

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        connection:
          db-type: postgres
          url: jdbc:postgresql://localhost:5432/bookstore-example
          username: postgres
          password: password
        show_sql: true
        jdbc:
          time_zone: UTC
    reactive: true

netty:
  default:
    allocator:
      max-order: 3
